workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Clean & Get Packages
        script: |
          flutter clean
          flutter pub get
      
      - name: Force Update Deployment Target
        script: |
          cd ios
          find . -name "project.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' {} +
          cd ..

      - name: Force Generate iOS Config
        script: |
          flutter build ios --config-only --no-codesign --debug
      
      - name: Install & Update CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --repo-update
      
      - name: Copy Firebase Config (ATOM BOMB) 💣
        script: |
          # Dosyayi hem köke hem de Runner klasörüne atıyoruz, garanti olsun
          cp ios/Runner/GoogleService-Info.plist ios/GoogleService-Info.plist
          
          # Xcode'un içine gömmek için özel hamle
          echo "GoogleService-Info.plist dosyasini kontrol ediyoruz..."
          ls -l ios/Runner/GoogleService-Info.plist

      - name: Build .app for Simulator
        script: |
          flutter build ios --debug --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app