workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Clean & Get Packages
        script: |
          flutter clean
          flutter pub get
      
      - name: Force Generate iOS Config (Windows Fix)
        script: |
          flutter build ios --config-only --no-codesign --debug
      
      - name: Install & Update CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          # Podfile'i zorla 15.0 yap (Garanti olsun)
          sed -i '' "s/platform :ios, .*/platform :ios, '15.0'/" Podfile
          pod install --repo-update
      
      - name: Build .app for Simulator
        script: |
          cd ..
          flutter build ios --debug --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app