workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter paketlerini getir
        script: |
          flutter packages pub get
      - name: Pods yükle
        script: |
          find . -name "Podfile" -exec dir "{}" \;
          cd ios && pod install
      - name: Simülatör için derle (İmzasız)
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app